FROM python:3.10 

RUN python -m venv /pyenv
RUN /pyenv/bin/pip install --no-cache-dir --upgrade pip
RUN /pyenv/bin/pip install --no-cache-dir numpy pandas tsai ipython paho-mqtt influxdb_client

ENV PATH="/pyenv/bin:${PATH}"
